### Get all products
GET http://localhost:9000/products

### Get one product
GET http://localhost:9000/products/PRODUCT_ID

### Add a product
POST http://localhost:9000/products
Content-Type: application/json

{
    "name": "Hill's Science Diet Adult Sensitive Stomach & Skin Chicken Recipe Dry Dog Food, 36 lbs.",
    "description": "Hill's Science Diet Sensitive Stomach & Skin dry dog food is highly digestible for optimal nutrient absorption & easy stool pick-up. Gentle on stomachs while nourishing skin & promoting a lustrous coat. With beet pulp, a nourishing prebiotic fiber Highly digestible food that is gentle on the stomach Vitamin E & Omega-6 fatty acids for skin & coat nourishment Natural ingredients with added vitamins, minerals and amino acids.",
    "image": "hills_sensitive.avif",
    "price": 98.99,
    "quantity": 50,
    "categoryName": "food",
    "petTypeName": "dog"
}

### Update a product
PATCH http://localhost:9000/products/PRODUCT_ID
Content-Type: application/json

{
    "name": "Updated Toy Name"
}

### Add a category
POST http://localhost:9000/categories
Content-Type: application/json

{
    "categoryName": "supplies",
    "petTypeName": "cat"
}

### Add a pet type
POST http://localhost:9000/pet-types
Content-Type: application/json

{
    "petTypeName": "cat"
}
