GET http://localhost:9000/

####
GET http://localhost:9000/6747cc66a379f77f2d614d2c

###
POST http://localhost:9000/
Content-Type: application/json

{
    "petTypeName": "dog",
    "categoryName": "toys",
    "product": {
        "name": "Chew Toy",
        "description": "A durable chew toy for dogs.",
        "image": "https://example.com/chew-toy.jpg",
        "price": 12.99,
        "quantity": 50
    }
}

###
POST http://localhost:9000/
Content-Type: application/json

{
    "petTypeName": "cat",
    "categoryName": "food",
    "product": {
        "name": "Meow Mix",
        "description": "A quality cat food.",
        "image": "https://example.com/meow-mix.jpg",
        "price": 8.99,
        "quantity": 10
    }
}

###
POST http://localhost:9000/
Content-Type: application/json

{
    "petTypeName": "dog",
    "categoryName": "food",
    "product": {
        "name": "Gravy Train",
        "description": "Just add hot water to make a gravy-licous dog food.",
        "image": "https://example.com/gravy-train.jpg",
        "price": 13.99,
        "quantity": 22
    }
}

###
PATCH http://localhost:9000/6747cc66a379f77f2d614d2c
Content-Type: application/json

{
    "petTypeName": "dog"
}