### Get all products
GET http://localhost:9000/products

### Get products by category
GET http://localhost:9000/products/by-pet-type/dog

### Get one product
GET http://localhost:9000/products/674b7bd11e1d787c26b74962

### Add a product
POST http://localhost:9000/products
Content-Type: application/json

{
    "name": "Hill's Science Diet Adult Sensitive Stomach & Skin Chicken Recipe Dry Dog Food, 36 lbs.",
    "description": "Hill's Science Diet Sensitive Stomach & Skin dry dog food is highly digestible for optimal nutrient absorption & easy stool pick-up. Gentle on stomachs while nourishing skin & promoting a lustrous coat. With beet pulp, a nourishing prebiotic fiber Highly digestible food that is gentle on the stomach Vitamin E & Omega-6 fatty acids for skin & coat nourishment Natural ingredients with added vitamins, minerals and amino acids.",
    "image": "hills_sensitive.avif",
    "price": 98.99,
    "quantity": 50,
    "categoryName": "food",
    "petTypeName": "dog"
}

### Add a product (incomplete data: missing categoryName): SHOULD FAIL
POST http://localhost:9000/products
Content-Type: application/json

{
    "name": "Nylabone Healthy Edibles Roast Beef Flavored Dog Bone Chews, Small, Count of 2.",
    "description": "Nylabone Healthy Edibles Roast Beef Flavored Dog Bone Chews. Completely edible and digestible mouth watering flavored chews. Natural, gluten-free, no artificial preservatives, salt or sugar. Includes added vitamins and minerals for a delicious and nutritious treat.",
    "image": "nylabone_2_pack.avif",
    "price": 4.99,
    "quantity": 22,
    "petTypeName": "dog"
}

### Update a product
PATCH http://localhost:9000/products/674b7bd11e1d787c26b74962
Content-Type: application/json

{
    "name": "Nylabone Healthy Edibles Roast Beef Flavored Dog Bone Chews, Small, 2 count"
}

### Add a category (must pre-populate category before attempting to POST a product of that category)
POST http://localhost:9000/categories
Content-Type: application/json

{
    "categoryName": "supplies",
    "petTypeName": "cat"
}

### Add a pet type (must pre-populate petType before attempting to POST a product of that petType)
POST http://localhost:9000/pet-types
Content-Type: application/json

{
    "petTypeName": "cat"
}
